[package]
name = "cpu-emulator-6502-8bitpickles"
version = "0.1.0"
authors = ["Marc Easen <marc@easen.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
